// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
    export interface GlobalComponents {
        HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
        NButton: typeof import("naive-ui")["NButton"];
        NCard: typeof import("naive-ui")["NCard"];
        NConfigProvider: typeof import("naive-ui")["NConfigProvider"];
        NGlobalStyle: typeof import("naive-ui")["NGlobalStyle"];
        NLayout: typeof import("naive-ui")["NLayout"];
        NLayoutContent: typeof import("naive-ui")["NLayoutContent"];
        NLayoutFooter: typeof import("naive-ui")["NLayoutFooter"];
        NLayoutHeader: typeof import("naive-ui")["NLayoutHeader"];
        NSpace: typeof import("naive-ui")["NSpace"];
    }
}
